---

nodejs_version: 5.3.0
nodejs_install_url: "https://nodejs.org/dist/v{{ nodejs_version }}/node-v{{ nodejs_version }}.pkg"
nodejs_versions:
  - lts
  - stable
nodejs_npm_packages:
  - bower
  - grunt-cli
  - jshint
  - node-sass
  - n
  - uglify-js
  - uglifycss
  - yo
