---

- name: check for sequel pro
  command: stat /Applications/Sequel\ Pro.app
  register: sequelpro_exists
  ignore_errors: yes
  tags:
    - lamp

- name: download sequel pro
  when: sequelpro_exists | failed
  get_url: url={{ sequelpro_install_url }} dest=/tmp/sequelpro.dmg mode=0440
  tags:
    - lamp

- name: mount sequel pro
  when: sequelpro_exists | failed
  command: hdiutil attach /tmp/sequelpro.dmg
  tags:
    - lamp

- name: copy sequel pro to applications folder
  when: sequelpro_exists | failed
  synchronize:
    src: "{{ sequelpro_volume }}/Sequel Pro.app"
    dest: /Applications
    perms: yes
  tags:
    - lamp

- name: unmount sequel pro
  when: sequelpro_exists | failed
  command: hdiutil detach "{{ sequelpro_volume }}"
  tags:
    - lamp

- name: check for robomongo
  command: stat /Applications/Robomongo.app
  register: robomongo_exists
  ignore_errors: yes
  tags:
    - mean

- name: download robomongo
  when: robomongo_exists | failed
  get_url: url={{ robomongo_install_url }} dest=/tmp/robomongo.dmg mode=0440
  tags:
    - mean

- name: mount robomongo
  when: robomongo_exists | failed
  command: hdiutil attach /tmp/robomongo.dmg
  tags:
    - mean

- name: copy robomongo to applications folder
  when: robomongo_exists | failed
  synchronize:
    src: "{{ robomongo_volume }}/Robomongo.app"
    dest: /Applications
    perms: yes
  tags:
    - mean

- name: unmount robomongo
  when: robomongo_exists | failed
  raw: hdiutil detach "{{ robomongo_volume }}"
  tags:
    - mean
